renderer n shit

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -35,6 +35,39 @@ if [ $? -ne 0 ]; then
 fi
 '''
 
+[tasks.inject-gdb]
+workspace = false
+script = '''
+#!/bin/bash
+pid=$(pidof tf_linux64)
+if [ -z "$pid" ]; then
+    echo "tf2 not running"
+    exit 1
+fi
+
+echo $pid
+lib_path=$(cargo build --message-format=json | jq -r 'select(.profile.test == false) | select(.target.name == "oxidus" ) | .filenames[0]')
+if [ ! -f "$lib_path" ]; then
+    echo "liboxidus.so not found"
+    exit 1
+fi
+
+cp "$lib_path" /tmp/liboxidus.so
+
+sudo rust-gdb -q \
+    -ex "attach $pid" \
+    -ex "set \$dlopen = (void* (*)(char*, int))dlopen" \
+    -ex "set \$dlerror = (char* (*)(void))dlerror" \
+    -ex "call \$dlopen(\"/tmp/liboxidus.so\", 2)" \
+    -ex "call \$dlerror()" \
+    -ex "continue"
+
+if [ $? -ne 0 ]; then
+    echo "failed to inject"
+    exit 1
+fi
+'''
+
 [tasks.unload]
 workspace = false
 script = '''
@@ -80,7 +113,7 @@ export LD_LIBRARY_PATH='bin/linux64';
 #export LD_DEBUG=all;
 #export LD_DEBUG=libs;
 export DXVK_HUD=1
-./tf_linux64 -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -nobreakpad
+./tf_linux64 -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -nobreakpad -gl
 #ltrace -f -o ~/ltrace.log ./tf_linux64 -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -nobreakpad
 #strace -f -o ~/strace.log ./tf_linux64 -game tf -steam -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime -nobreakpad
 '''
